defaults:
  - data: default
  - params: default
  - process: default
  - _self_

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d_%H-%M-%S}
  job:
    chdir: true
  sweep:
    dir: multirun/${now:%Y-%m-%d_%H-%M-%S}
    subdir: ${hydra.job.num}

paths:
  root: ${oc.env:PROJECT_ROOT}
  data_dir: ${paths.root}/data
  raw_dir: ${paths.data_dir}/raw
  processed_dir: ${paths.data_dir}/processed
  estimated_dir: ${paths.data_dir}/estimated
  final_dir: ${paths.data_dir}/final